apiVersion: 1
groups:
    - orgId: 1
      name: anomaly-evaluateion-group
      folder: alerts
      interval: 1m
      rules:
        - uid: aet7mfw4dn6yoc
          title: Anomaly scores station 1
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus_uid
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: prometheus_uid
                disableTextWrap: false
                editorMode: builder
                expr: anomaly_score{station_id="station_1"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: '{{station_id}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: dddfd6d0-eb6d-4105-b8ec-8bb948e1313a
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: dddfd6d0-eb6d-4105-b8ec-8bb948e1313a
            __panelId__: "3"
            summary: Anomaly on station 1
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: det7mubo6ufi8b
          title: Anomaly scores
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus_uid
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: prometheus_uid
                disableTextWrap: false
                editorMode: builder
                expr: anomaly_score{station_id="station_2"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: '{{station_id}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: dddfd6d0-eb6d-4105-b8ec-8bb948e1313a
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: dddfd6d0-eb6d-4105-b8ec-8bb948e1313a
            __panelId__: "3"
            summary: Anomaly on station 2
          isPaused: false
          notification_settings:
            receiver: grafana-default-email