global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'model_service'
    static_configs:
      - targets : ['model_service:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
