{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Anomalies rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(anomalies_detected_total{station_id=~\".*\"}[1m])",
     "legendFormat": "{{station_id}}"
    }
   ]
  },
  {
   "title": "Anomalies detected total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anomalies_detected_total", "legendFormat": "{{station_id}}" }
   ]
  },
  {
   "title": "Anomaly scores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "last_anomaly_score", "legendFormat": "{{station_id}}" }
   ]
  },
  {
   "title": "Request duradion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum/ http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}